:concurrency: 3
:timeout: 60
:verbose: true
:queues:  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - mailers
  - default
  - sentry
  - active_storage_analysis
  - active_storage_purge
